#!/bin/bash -l 
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:01:00 
#SBATCH -J My_267_job 
#SBATCH -o MyOutputFile.%j.out
#SBATCH -e MyErrorFile.%j.err


srun -n 1 -N 1 --cpu-freq=2400000 ./benchmark-naive
